name: test-purchase

on:
  push:
    branches-ignore:
      - live
      - main
    paths:
      - packages/purchase/**

jobs:
  run-tests:
    name: run-test-purchase-tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - name: Run purchase unit tests
        run: npm run test-purchase
