name: deploy-billing ci/cd-workflow

on:
  push:
    branches:
      - live
    paths:
      - packages/billing/*

jobs:
  deploy-billing-service:
    name: deploy-billing-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy billing service
        run: npm run deploy-billing
