name: deploy-connectivity

on:
  push:
    branches:
      - live
    paths:
      - packages/connectivity/**

jobs:
  deploy-connectivity-service:
    name: deploy-connectivity-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: npm install
      - name: Deploy connectivity service
        run: npm run deploy-connectivity
