name: deploy-purchase

on:
  push:
    branches:
      - live
    paths:
      - packages/purchase/**

jobs:
  deploy-purchase-service:
    name: deploy-purchase-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: npm install
      - name: Deploy purchase service
        run: npm run deploy-purchase
