name: live ci/cd

on:
  push:
    branches:
      - live

jobs:
  run-tests:
    name: run-tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Fetch history
        run:  git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: lerna run deploy --since main
