name: live ci/cd
"on":
  push:
    branches:
      - live
jobs:
  analyse-services:
    name: analyse-services
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: live
          filters: |
            purchase_change:
              - '.github/**'
              - 'lerna.json'
              - 'package.json'
              - 'package-lock.json'
              - 'packages/purchase/**'
            billing_change:
              - '.github/**'
              - 'lerna.json'
              - 'package.json'
              - 'package-lock.json'
              - 'packages/billing/**'
            connectivity_change:
              - '.github/**'
              - 'lerna.json'
              - 'package.json'
              - 'package-lock.json'
              - 'packages/connectivity/**'
            after_all_change:
              - 'lerna.json'
              - 'package.json'
              - 'package-lock.json'
              - 'packages/after_all/**'
    outputs:
      purchase_change: "${{ steps.changes.outputs.purchase_change }}"
      billing_change: "${{ steps.changes.outputs.billing_change }}"
      connectivity_change: "${{ steps.changes.outputs.connectivity_change }}"
      after_all_change: "${{ steps.changes.outputs.after_all_change }}"

  deploy-purchase-service:
    name: deploy-purchase-service
    runs-on:
      - ubuntu-latest
    needs: analyse-services
    if: "${{ needs.analyse-services.outputs.purchase_change == 'true' }}"
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy purchase service
        run: npm run deploy-purchase
  deploy-connectivity-service:
    name: deploy-connectivity-service
    runs-on:
      - ubuntu-latest
    needs: analyse-services
    if: "${{ needs.analyse-services.outputs.connectivity_change == 'true' }}"
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy connectivity service
        run: npm run deploy-connectivity
  deploy-billing-service:
    name: deploy-billing-service
    runs-on:
      - ubuntu-latest
    needs: analyse-services
    if: "${{ needs.analyse-services.outputs.billing_change == 'true' }}"
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy billing service
        run: npm run deploy-billing
  deploy-after-all-service:
    name: deploy-after-all-service
    runs-on:
      - ubuntu-latest
    # continue-on-error: false
    # if: ${{ !failure() }}
    needs:
      - deploy-purchase-service
      - deploy-connectivity-service
      - deploy-billing-service
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy after all service
        run: npm run deploy-after-all
