name: live ci/cd

on:
  push:
    branches:
      - live

jobs:
  deploy-purchase-service:
    name: deploy-purchase-service
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Deploy purchase service
        run: npm run deploy-purchase

  deploy-connectivity-service:
    name: deploy-connectivity-service
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Deploy connectivity service
        run: npm run deploy-connectivity

  deploy-billing-service:
    name: deploy-billing-service
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Deploy billing service
        run: npm run deploy-billing