name: live ci/cd

on:
  push:
    branches:
      - live

jobs:
  deploy-live:
    name: deploy-live
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Deploy services
        run: lerna run deploy --since origin/live
