name: Job Conditionals

on:
  push:
    branches-ignore:
      - live
      - main

jobs:
  a:
    if: true
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
  b:
    if: true
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
      # - name: Try to fail
      #   run: exit 1
  c:
    if: true
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
      # - name: Try to fail
      #   run: exit 1

  # default:
  #   needs: [a, b, c]
  #   if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: echo "Hello world"

  # always-no-contains-failure:
  #   needs: [a, b, c]
  #   if: ${{ always() && !(contains(needs.*.result, 'failure')) }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: echo "Hello world"

  # no-contain-failure:
  #   needs: [a, b, c]
  #   if: ${{  !(contains(needs.*.result, 'failure')) }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: echo "Hello world"

  # no-failure:
  #   needs: [a, b, c]
  #   if: ${{  !failure() }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: echo "Hello world"

  # always-success-no-failure:
  #   needs: [a, b, c]
  #   runs-on: ubuntu-latest
  #   if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
  #   steps:
  #     - run: echo ${{needs.a.result}}
  #     - run: echo ${{needs.b.result}}
  #     - run: echo ${{needs.c.result}}

  always:
    needs: [a, b, c]
    if: ${{  always() }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"

  after-always:
    needs: [always]
    if: ${{ always() && !(contains(needs.*.result, 'skipped')) }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
      - run: echo ${{needs.always.a.result}}
      - run: echo ${{needs.always.b.result}}
      - run: echo ${{needs.always.c.result}}
      - run: echo ${{needs.always.result}}
