name: test-connectivity

on:
  push:
    branches-ignore:
      - live
      - master
    paths:
      - packages/connectivity/**

jobs:
  run-tests:
    name: run-test-connectivity-tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Run connectivity unit tests
        run: npm run test-connectivity
