name: test ci/cd

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Run purchase tests
        run: npm run test-purchase
      - name: Run connectivity tests
        run: npm run test-connectivity
      - name: Run billing tests
        run: npm run test-billing
