name: test ci/cd-workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: [ubuntu-latest]
    needs: generate-configs
    steps:
      - uses: actions/checkout@master
      - name: Run unit tests
        run: npm run test

  deploy-purchase-service:
    name: deploy-purchase-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy purchase service
        run: npm run deploy-purchase

  deploy-billing-service:
    name: deploy-billing-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy billing service
        run: npm run deploy-billing

  deploy-connectivity-service:
    name: deploy-connectivity-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy connectivity service
        run: npm run deploy-connectivity
