name: test-purchase

on:
  push:
    branches-ignore:
      - live
      - master
    paths:
      - packages/purchase/**
    

jobs:
  run-tests:
    name: run-test-purchase-tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Run purchase unit tests
        run: npm run test-purchase

  deploy-purchase-service:
    name: deploy-purchase-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy purchase service
        run: npm run deploy-purchase

  deploy-billing-service:
    name: deploy-billing-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy billing service
        run: npm run deploy-billing
        env:
          MOLOTOV_BILLING: 123

  deploy-connectivity-service:
    name: deploy-connectivity-service
    runs-on: [ubuntu-latest]
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy connectivity service
        run: npm run deploy-connectivity
