name: test ci/cd

on:
  push:
    branches-ignore:
      - live
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: lerna run test --since main
